#!/usr/bin/env python3

import argparse
import scalavista

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', help='switch on debug mode',
                    action='store_true')
parser.add_argument('-r', '--recursive', help='look for Scala source files in all subdirectories - applies only in the absence of a scalavista.json file',
                    action='store_true')
args = parser.parse_args()

scalavista.launch(args.debug, args.recursive)
