#!/usr/bin/env python3

import argparse
import scalavista

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', help='switch on debug mode',
                    action='store_true')
args = parser.parse_args()

scalavista.launch(args.debug)
